name: main_workflow

# Ejecuta el workflow en un push a la rama especificada
on:
  push:
    branches:
      - nodejs_test_error

jobs:
  linter-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup node version
      - name: Setting node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Linter execution
      - name: Linter execution
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          LINTER_RULES_PATH: /
          JAVASCRIPTS_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
  test-execution:
    runs-on: ubuntu-latest
    needs: linter-execution
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Jest
        run: npm install jest --legacy-peer-deps
      - name: Run Jest Test
        run: npm run test
        id: jest
        continue-on-error: true
      - name: Fails
        if: steps.jest.outcome != 'success'
        run: echo "Se ha producido un error" && exit 1
  environment_test_execution:
    runs-on: ubuntu-latest
    needs: [linter-execution, test-execution]
    steps:
      - name: Hello world environment
        uses: adeloyedeji/github-actions-hello@v1.0
        with:
          who-to-greet: "DAW Santiago López"
